In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df=pd.read_csv("/content/healthcare_data_for_task - healthcare_data_for_task (1).csv")

In [12]:
df.head()

,Patient_ID,Age,Gender,Blood_Type,Medical_Condition,Medical_Code,Date_of_Admission,Discharge_Date,Admission_Type,Billing_Amount
0,P0001,47,Male,AB+,Heart Disease,HEA004,2025-05-10,2025-05-16,Emergency,23218.31
1,P0002,62,Female,AB-,Diabetes,DIA001,2025-12-31,2026-01-02,Emergency,47010.56
2,P0003,36,Male,AB-,Heart Disease,HEA004,2025-11-10,2025-11-27,Emergency,39619.01
3,P0004,51,Male,A+,Heart Disease,HEA004,2023-05-02,2023-05-07,Elective,35963.71
4,P0005,30,Male,A+,Diabetes,DIA001,2024-04-11,2024-04-17,Urgent,64615.93

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         1000 non-null   object
 1   Age                1000 non-null   int64
 2   Gender             1000 non-null   object
 3   Blood_Type         1000 non-null   object
 4   Medical_Condition  1000 non-null   object
 5   Medical_Code       970 non-null    object
 6   Date_of_Admission  1000 non-null   object
 7   Discharge_Date     1000 non-null   object
 8   Admission_Type     1000 non-null   object
 9   Billing_Amount     1000 non-null   float64
dtypes: float64(1), int64(1), object(8)
memory usage: 78.3+ KB

In [14]:
df.shape

(1000, 10)

In [15]:
df.describe()

               Age  Billing_Amount
count  1000.000000     1000.000000
mean     51.888000    77117.515720
std      19.256954    41955.242269
min      18.000000     5568.160000
25%      35.750000    40318.785000
50%      52.000000    77293.900000
75%      69.000000   113089.267500
max      85.000000   149921.800000

In [17]:
df["Medical_Code"]

0      HEA004
1      DIA001
2      HEA004
3      HEA004
4      DIA001
        ...
995    DIA001
996    DIA001
997    DIA001
998    DIA001
999    AST003
Name: Medical_Code, Length: 1000, dtype: object

In [22]:
df.isnull().sum()

Patient_ID            0
Age                   0
Gender                0
Blood_Type            0
Medical_Condition     0
Medical_Code         30
Date_of_Admission     0
Discharge_Date        0
Admission_Type        0
Billing_Amount        0
dtype: int64

In [28]:
df['Medical_Code']=df['Medical_Code'].fillna('Unknown')

In [30]:
df['Admission_Type']=(
    df['Admission_Type']
    .str.split()
    .str.title()
)